include: package:total_lints/package.yaml

analyzer:
  errors:
    # Don't require switch statements to be exhaustive (allow them to use the `default` case).
    no_default_cases: ignore

linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # Temporary for debugging (this is a temporary rule as it will hide errors)
    # https://dart.dev/tools/linter-rules/avoid_catches_without_on_clauses
    avoid_catches_without_on_clauses: false
