include: package:total_lints/package.yaml

linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    # Temporary for debugging (this is a temporary rule as it will hide errors)
    # https://dart.dev/tools/linter-rules/avoid_catches_without_on_clauses
    avoid_catches_without_on_clauses: false
